- name: Install MySQL libraries
  ansible.builtin.pip:
    name: "{{ item }}"
    executable: pip3.9
  loop:
  - cryptography
  - PyMySQL

- name: Install MySQL server
  ansible.builtin.package:
    name: mysql-server
    state: installed

- name: start and enable mysql server
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes

- name: Connect to MySQL server
  community.mysql.mysql_info:
    login_user: root
    login_password: "{{ lookup('amazon.aws.ssm', '/realproject/om/mysql-password', 'decrypt=False') }}"
    login_host: "{{ mysql_host }}"
  register: mysql_info
  ignore_errors: yes

- name: print the output
  ansible.builtin.debug:
    msg: "MySQL info: {{ mysql_info }}"

- name: Setup root password
  ansible.builtin.command: >
    mysql_secure_installation --set-root-pass
    {{ lookup('amazon.aws.ssm', '/realproject/om/mysql-password', 'decrypt=False') }}
  when: mysql_info.failed | bool
